[package]
name = "faker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
owo-colors = "3"
fake = { version = "2.4", features = ['chrono'] }
chrono = "0.4.19"
rand = "0.8"
